inputs:
  source:
    description: “The site handle to screenshot”
    required: true
  command:
    description: "The tweet.py command to run"
    required: true

runs:
  using: "composite"
  steps:
    - id: install-playwright
      name: Install Playwright dependencies
      run: |
        pipenv run shot-scraper install
        pipenv run python -m playwright install-deps
      shell: bash

    - id: shoot
      name: Take screenshot
      run: pipenv run python -m newshomepages.shoot ${{ inputs.command }} ${{ inputs.source }} -o _dist
      shell: bash

    - id: save
      name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.source }}
        path: _dist
        if-no-files-found: error
